namespace Illumi_CLI
{
    public enum TokenKind
    {
        WhitespaceToken,
        LeftBraceToken,
        RightBraceToken,
        Type_IntegerToken,
        Type_StringToken,
        Type_BooleanToken,
        IdentifierToken,
        UnrecognisedToken,
        WhileToken,
        PrintToken,
        IfToken,
        DigitToken,
        StringToken,
        LeftParenthesisToken,
        RightParenthesisToken,
        AssignmentToken,
        TrueToken,
        FalseToken,
        EquivalenceToken,
        AdditionToken,
        EndOfProgramToken,
        NotEqualToken,
        CommentToken,
        EndOfFileToken
    }
}
